Drim brain/software architecture
drim-dev/knowledge pull request #4
Opened 2024-02-13 21:48 UTC by sergey-rubtsov-05

Notes based on lecture [10-software-architecture](https://github.com/drim-dev/courses-cryptobank-microservices-01/tree/main/10-software-architecture)

2024-02-13 21:50 UTC, sergey-rubtsov-05 commented
@mitro Please, check this, what do you think about it? Does it fit with your idea about architecture notes?

2024-02-17 15:13 UTC, mitro requested changes

2024-02-17 15:13 UTC, mitro commented on architecture/ADR/README.md
> +- [Architecture Decision Records](#architecture-decision-records)
Folder names are in lower case, even if they are abbreviations. So let's rename `ADR` to `adr`. The same about `DDD`

2024-02-17 15:13 UTC, mitro commented on architecture/ADR/README.md
> +**Architecture Decision Record (ADR)** is a document that captures decisions made regarding the design and architecture of a
Two underscores (`__`text`__`) are used for the bold font throughout the repository. A single underscore (`_`text`_`) is used for the italics font. Please fix it in all files.

2024-02-17 15:13 UTC, mitro commented on architecture/ADR/README.md
> +- [Architecture Decision Records](#architecture-decision-records)
Good idea about the table of contents. I will be creating it also

2024-02-17 15:13 UTC, mitro commented on architecture/ADR/README.md
> +* https://adr.github.io/
Let's end each file with the blank line

2024-02-17 15:13 UTC, mitro commented on architecture/DDD/README.md
> +# 1. Domain-Driven Design
`1.` Is not consistent with the common structure of the pages

2024-02-17 15:13 UTC, mitro commented on architecture/DDD/README.md
> +- Bounded contexts
Let's use `*` instead of `-` for lists to be consistent with other documents

2024-02-17 15:13 UTC, mitro commented on architecture/diagrams/README.md
> +![Context Diagram (C1)](images/c1-context-diagram.png)
All `images` folders should be renamed to `_images`. I use an underscore to indicate that it is a well-known folder. `_lab` is another example

2024-02-17 15:13 UTC, mitro commented on architecture/feature-based-architecture/README.md
> +## 1.1. Screaming Architecture
Let's separate headers with blank lines

2024-02-17 15:13 UTC, mitro commented on architecture/feature-based-architecture/README.md
> +# 1. Feature-based architecture
`1.` and `1.1.` are unnecessary, in my opinion. Indexes are not used in other documents

2024-02-17 15:13 UTC, mitro commented on architecture/feature-based-architecture/README.md
> +<img src="images/vertical-slices.png" />
Should be ![Vertical slices](_images/vertical-slices.png) to be consistent with other documents

2024-02-17 17:33 UTC, sergey-rubtsov-05 commented on architecture/ADR/README.md
> +**Architecture Decision Record (ADR)** is a document that captures decisions made regarding the design and architecture of a
Okay. Also, I started to use [markdownlint extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint). A little investigation showed me that it's really popular, it is also used in [dotnet docs](https://github.com/dotnet/docs/blob/main/.markdownlint-cli2.jsonc). It is even possible to include it in [github workflow](https://github.com/dotnet/docs/blob/main/.github/workflows/markdownlint.yml).

Rule `MD050` will control it.

2024-02-17 17:35 UTC, sergey-rubtsov-05 commented on architecture/ADR/README.md
> +* https://adr.github.io/
Rule `MD047` will control it.

2024-02-17 17:35 UTC, sergey-rubtsov-05 commented on architecture/DDD/README.md
> +- Bounded contexts
Rule `MD004` will control it.

2024-02-17 17:37 UTC, sergey-rubtsov-05 commented on architecture/feature-based-architecture/README.md
> +## 1.1. Screaming Architecture
Rule `MD022` will control it.

2024-02-17 18:22 UTC, sergey-rubtsov-05 commented on architecture/DDD/README.md
> +# 1. Domain-Driven Design
Agree. I removed section numbers

2024-02-17 18:28 UTC, sergey-rubtsov-05 commented on architecture/feature-based-architecture/README.md
> +# 1. Feature-based architecture
Agree. Fixed it

2024-02-17 18:30 UTC, sergey-rubtsov-05 commented on architecture/feature-based-architecture/README.md
> +<img src="images/vertical-slices.png" />
Sorry, I am not sure what you mean.

2024-02-18 13:32 UTC, mitro commented on architecture/feature-based-architecture/README.md
> +<img src="images/vertical-slices.png" />
My bad. I used a formatting syntax and missed the fact that it would render as a link. I mean, we should use a single format for links. Square brackets, but not `<img>` tag

2024-02-18 13:53 UTC, mitro requested changes

2024-02-18 13:53 UTC, mitro commented on architecture/diagrams/README.md
> +![Context Diagram (C1)](images/c1-context-diagram.png)
You need to fix links to use `_images` as well.

2024-02-18 13:53 UTC, mitro commented on architecture/layered-architectures/README.md
> +# 1. Traditional Architectures
Indexes not removed

2024-02-18 13:53 UTC, mitro commented on architecture/layered-architectures/README.md
> +<img alt="Layered  Architecture" src="_images/layered-architecture.png" width="70%" />
Let's replace `<img>` with a square brackets format here and below

2024-02-18 13:53 UTC, mitro commented on architecture/modularity/README.md
> +* __Data coupling__ - When two modules interact with each other by means of passing data (as parameter). Data is passed between components.
Some bold formatting in the PR uses two underscores, while other parts use two stars. Let's use two underscores everywhere

2024-02-18 15:15 UTC, sergey-rubtsov-05 commented on architecture/modularity/README.md
> +* __Data coupling__ - When two modules interact with each other by means of passing data (as parameter). Data is passed between components.
Fixed it. Markdownlint extension unexpectedly ignored this places.

2024-02-18 15:33 UTC, mitro approved these changes

2024-02-18 15:33 UTC, merged