#dotnet-configuration: improve documentation
drim-dev/knowledge pull request #6
Opened 2024-09-08 20:24 UTC by sergey-rubtsov-05

I have tried to rewrite documentation in a more useful way. What do you think about it?

2024-09-08 20:27 UTC, sergey-rubtsov-05 commented
@duskembayev I think you will also be interested in seeing it.

2024-09-09 03:31 UTC, mitro approved these changes

2024-09-09 20:23 UTC, duskembayev requested changes
Great article! Minor changes are required.

2024-09-09 20:23 UTC, duskembayev commented on dotnet/configuration/README.md
> +## Sources of Options
Add information this is default sources. It can be changed or extended.

2024-09-09 20:23 UTC, duskembayev commented on dotnet/configuration/README.md
Add principle of including env specific `appsettings.{env}.json' config.

2024-09-09 20:23 UTC, duskembayev commented on dotnet/configuration/README.md
> +__Example:__
Remove the header, as in other sections.

2024-09-09 20:23 UTC, duskembayev commented on dotnet/configuration/README.md
> +export Services__UserService__Url=https://env-specific.url
Better to use a Windows-style command, or present both examples.

2024-09-09 20:23 UTC, duskembayev commented on dotnet/configuration/README.md
> +export Services__UserService__Timeout=00:02:00
Add information about separator "__".

2024-09-09 20:23 UTC, duskembayev commented on README.md
Let's add a section about named options.

2024-09-11 19:51 UTC, duskembayev approved these changes

2024-09-11 19:53 UTC, sergey-rubtsov-05 commented
@mitro Please, could you merge this PR?

2024-09-12 05:53 UTC, merged